# Generated by Django 4.0.4 on 2023-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_tbl_cart_tbl_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
